# Generated by Django 2.2.6 on 2019-10-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Nome')),
                ('noticia', models.CharField(max_length=255, verbose_name='CPF')),
            ],
        ),
    ]
